In [1]:
import numpy as np
import pandas as pd
import math 
import random as rn
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris

# iris = pd.read_csv('irisdata.csv',header=None,names=('Sepal L','Sepal W','Petal L','Petal W','Class'))
# iris = iris.head(100)  # Taking only first 100 rows
# iris.head()

In [4]:
iris = load_iris()
x = iris.data
y = iris.target
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [5]:
df = pd.DataFrame(x,columns=['Sepal L','Sepal W','Petal L','Petal W'])
df.head()

Sepal L  Sepal W  Petal L  Petal W
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2
3      4.6      3.1      1.5      0.2
4      5.0      3.6      1.4      0.2

In [6]:
df['label'] = y
df.head()

Sepal L  Sepal W  Petal L  Petal W  label
0      5.1      3.5      1.4      0.2      0
1      4.9      3.0      1.4      0.2      0
2      4.7      3.2      1.3      0.2      0
3      4.6      3.1      1.5      0.2      0
4      5.0      3.6      1.4      0.2      0

In [7]:
df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [9]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.35)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(97, 4)
(53, 4)
(97,)
(53,)


In [12]:
from sklearn.linear_model import SGDClassifier

In [22]:
m1 = SGDClassifier(loss='log',max_iter=500,eta0=0.001)
m1.fit(x_train,y_train)

SGDClassifier(eta0=0.001, loss='log', max_iter=500)

In [23]:
# Accuracy
print('Training Score',m1.score(x_train,y_train))
print('Testing Score',m1.score(x_test,y_test))

Training Score 0.5360824742268041
Testing Score 0.5849056603773585


In [24]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[2 2 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 2 1 1 2 1 1 1 1 1 1 0
 1 1 1 1 2 1 2 0 1 1 1 1 1 0 1 1]


In [25]:
cm = confusion_matrix(y_test,ypred_m1)
print(cm)
print(classification_report(y_test,ypred_m1))

[[ 5 16  0]
 [ 0 20  0]
 [ 0  6  6]]
              precision    recall  f1-score   support

           0       1.00      0.24      0.38        21
           1       0.48      1.00      0.65        20
           2       1.00      0.50      0.67        12

    accuracy                           0.58        53
   macro avg       0.83      0.58      0.57        53
weighted avg       0.80      0.58      0.55        53

