In [6]:
import numpy as np
print(np.__version__)

1.19.5


In [7]:
print(len(dir(np)))

618


## Numpy array functions

In [11]:
r1 = [[12,13,4],[15,17,16],[18,19,11],[16,22,20]]
a1 = np.array(r1)
print(a1)
print(a1.shape)
print(a1.ndim)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]
(4, 3)
2


### a) np.sum()

In [12]:
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [17]:
a1.sum()

183

In [18]:
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [21]:
# Row wise addition, axis=1
print(a1.sum(axis=1))
# Column wise addition, axis=0
print(a1.sum(axis=0))

[29 48 48 58]
[61 71 51]


### b) np.max() and np.min()

In [22]:
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [24]:
print(np.max(a1))
print(np.min(a1))
print(a1)

22
4
[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [151]:
# axis=1 => Rows
# axis=0 => Columns
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))
print(np.min(a1,axis=0))
print(np.min(a1,axis=1))

[18 22 20]
[13 17 19 22]
[12 13  4]
[ 4 15 11 16]


### c) np.argmax() and np.argmin()
<b>np.argmax()</b> - Returns the indices of the maximum values along an axis <br>  
<b>np.argmin() </b>- Returns the indices of the minimum values along an axis 

In [25]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
print(p1)

[12 14  7 79 32 45 28  4 17]


In [26]:
print(np.max(p1))
print(np.min(p1))

79
4


In [28]:
print(np.argmax(p1))
print(np.argmin(p1))

3
7


In [33]:
print(p1)
print(p1[3])
max_value = p1[np.argmax(p1)]
min_value = p1[np.argmin(p1)]
print('Max_value is ',max_value)
print('Min_value is ',min_value)

[12 14  7 79 32 45 28  4 17]
79
Max_value is  79
Min_value is  4


In [34]:
r2 = [[16,15,21],[15,16,8],[19,2,18],[9,12,13]]
p2 = np.array(r2)
print(p2)

[[16 15 21]
 [15 16  8]
 [19  2 18]
 [ 9 12 13]]


In [36]:
print(np.argmax(p2,axis=0))  # column wise
print(np.argmin(p2,axis=0))  # column wise
print(np.argmax(p2,axis=1))  # row wise
print(np.argmin(p2,axis=1))  # row wise

[2 1 0]
[3 2 1]
[2 1 0 2]
[1 2 1 0]


### d) np.sort

In [39]:
r1 = np.array([34,23,56,12,39])
print(r1)          

[34 23 56 12 39]


In [41]:
r2 = np.sort(r1) # ascending order
print(r2)
r2 = np.sort(r1)[::-1] # descending order
print(r2)

[12 23 34 39 56]
[56 39 34 23 12]


In [44]:
r1 = np.sort(r1)
print(r1)

[12 23 34 39 56]


In [45]:
r3 = np.array([[11,21,18],[24,35,16],[7,14,3]])
print(r3)

[[11 21 18]
 [24 35 16]
 [ 7 14  3]]


In [46]:
# sorts row wise
r4 = np.sort(r3,axis=1)
print(r4)
# sorts column wise
r5 = np.sort(r3,axis=0)
print(r5)

[[11 18 21]
 [16 24 35]
 [ 3  7 14]]
[[ 7 14  3]
 [11 21 16]
 [24 35 18]]


In [47]:
r6 = np.sort(r3) # default sort order is row wise
print(r6)

[[11 18 21]
 [16 24 35]
 [ 3  7 14]]


### e) np.where() - returns index position for the matching conditions

In [48]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
print(p1)

[12 14  7 79 32 45 28  4 17]


In [51]:
n2 = np.where(p1%3==0)
print(n2)
print(p1[np.where(p1%3==0)])

(array([0, 5], dtype=int64),)
[12 45]


In [52]:
print(p1)
print(np.where(p1 < 20))
print(p1[np.where(p1 < 20)])

[12 14  7 79 32 45 28  4 17]
(array([0, 1, 2, 7, 8], dtype=int64),)
[12 14  7  4 17]


#### Type-2

In [54]:
print(p1)
t1 = np.where(p1 < 20, p1+5, p1*2)
# if p1<20, then add 5 to those values, else multiply them by 2
print(t1)
t2 = np.where(p1%2==0, p1+10, p1-7)
# if p1%2==0, then add 10 to those values, else subtract 7 from them
print(t2)

[12 14  7 79 32 45 28  4 17]
[ 17  19  12 158  64  90  56   9  22]
[22 24  0 72 42 38 38 14 10]


In [55]:
w1 = np.array([[1,2,7],[3,4,-8],[5,6,0]])
print(w1)

[[ 1  2  7]
 [ 3  4 -8]
 [ 5  6  0]]


In [56]:
print(np.where(w1%2==0))
print(w1[np.where(w1%2==0)])

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 1, 2, 1, 2], dtype=int64))
[ 2  4 -8  6  0]


In [59]:
print(w1)
t1 = np.where(w1%2==0,w1+5,w1-5)
print(t1)

[[ 1  2  7]
 [ 3  4 -8]
 [ 5  6  0]]
[[-4  7  2]
 [-2  9 -3]
 [ 0 11  5]]


### f) np.extract() - 
Directly returns the values on which conditions are applied,using the second parameter as array name

In [60]:
print(p1)
t1 = np.extract(p1>20, p1)
print(t1)
t2 = np.extract(p1%3!=0,p1)
print(t2)

[12 14  7 79 32 45 28  4 17]
[79 32 45 28]
[14  7 79 32 28  4 17]


In [61]:
w1 = np.array([[1,2,7],[3,4,8],[5,6,13]])
print(w1)

[[ 1  2  7]
 [ 3  4  8]
 [ 5  6 13]]


In [62]:
w2 = np.extract(w1%3!=0,w1)
print(w2)

[ 1  2  7  4  8  5 13]


In [64]:
res = w1[w1%3!=0]
print(res)

[ 1  2  7  4  8  5 13]


### g) np.concatenate()
Join a sequence of arrays along an existing axis.

In [66]:
w1 = np.array([12,13,14,15])
w2 = np.array([18,19,20,21,22])
print(w1)
print(w2)

[12 13 14 15]
[18 19 20 21 22]


In [71]:
r1 = np.concatenate([w1,w2])
print(r1)
r2 = np.concatenate([w2,w1])
print(r2)

[12 13 14 15 18 19 20 21 22]
[18 19 20 21 22 12 13 14 15]


In [74]:
d1 = np.array([[1,2,3],[4,5,6]])
d2 = np.array([[7,8,9],[10,11,13]])
print(d1)
print(d2)
print(d1.shape,d2.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 13]]
(2, 3) (2, 3)


In [76]:
r2 = np.concatenate([d1,d2],axis=0)  # column wise (Column wise append)
print(r2)
r3 = np.concatenate([d1,d2],axis=1) # row wise (row wise append)
print(r3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 13]]


### Iterating over numpy array - np.nditer()

In [78]:
p1 = np.array([12, 14,  7, 79, 32, 45])
print(p1)
type(p1)

[12 14  7 79 32 45]


numpy.ndarray

In [82]:
for i in p1:
    print(i)

12
14
7
79
32
45


In [83]:
for i in np.nditer(p1):
    print(i)

12
14
7
79
32
45


In [84]:
n1 = np.arange(2,70,8).reshape(3,3)
print(n1)

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]


In [87]:
# Row wise Iteration
for i in n1:
    print(i)

[ 2 10 18]
[26 34 42]
[50 58 66]


In [89]:
# Element wise Iteration
for i in np.nditer(n1):
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [90]:
print(n1)

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]


In [182]:
for i in np.nditer(n1):  
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [96]:
print(n1)
for i in np.nditer(n1,order='K'):  # order= 'C', iterates element row wise
    print(i,end=' ')
    
# order='A','K'

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]
2 10 18 26 34 42 50 58 66 

In [92]:
print(n1)
for i in np.nditer(n1,order='F'):  # order= 'F', print element column wise
    print(i,end=' ')

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]
2 26 50 10 34 58 18 42 66 

In [98]:
n2 = np.arange(100,109).reshape(3,3)
print(n2)
print(n1)

[[100 101 102]
 [103 104 105]
 [106 107 108]]
[[ 2 10 18]
 [26 34 42]
 [50 58 66]]


In [101]:
for x,y in np.nditer([n1,n2]):  # row wise
    print(x,y)

2 100
10 101
18 102
26 103
34 104
42 105
50 106
58 107
66 108


In [102]:
for x,y in np.nditer([n1,n2],order='F'):  # column wise
    print(x,y)

2 100
26 103
50 106
10 101
34 104
58 107
18 102
42 105
66 108


## Matrix related Operations  - Multiply, Transpose, Flatten

In [104]:
r1 = np.arange(2,20,2).reshape(3,3)
print(r1)  

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [108]:
print(r1.T) # T = Transpose
print(r1.transpose())
print(np.transpose(r1))

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


In [110]:
print(r1)
print(r1.flatten())           # Flatten the row wise
print(r1.flatten(order='F'))  # Flatten the column wise 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 2  8 14  4 10 16  6 12 18]


In [114]:
a1 = np.array([8,5,0,2,9,6,4,1,7]).reshape(3,3)
a2 = np.array([3,7,9,4,1,0,5,6,2]).reshape(3,3)
print(a1)
print(a2)
print(a1.shape)
print(a2.shape)

[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]
(3, 3)
(3, 3)


### Matrix Multiplication

In [116]:
# Actual Matrix multiplication
r2 = np.matmul(a1,a2)
print(r2)

[[44 61 72]
 [72 59 30]
 [51 71 50]]


In [117]:
# Actual Matrix multiplication
r2 = np.dot(a1,a2)
print(r2)

[[44 61 72]
 [72 59 30]
 [51 71 50]]


In [128]:
w1 = np.arange(2,8).reshape(2,3)  # (2,3)   # w1(3,2) w2(2,3) => res(3,3)
print(w1)
w2 = np.arange(10,16).reshape(3,2) # (3,2)
print(w2)
res1 = np.dot(w1,w2)
print(res1)

# a1(n,m), a2(p,q)
# => if m=p
# => resultant shape => (n,q)

[[2 3 4]
 [5 6 7]]
[[10 11]
 [12 13]
 [14 15]]
[[112 121]
 [220 238]]


In [127]:
w1 = np.arange(1,16).reshape(5,3)  # (5,3)
print(w1)
w2 = np.arange(10,16).reshape(3,2) # (3,2)
print(w2)
res1 = np.dot(w1,w2)
print(res1)

# a1(n,m), a2(p,q)
# => if m=p
# => resultant shape => (n,q)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[10 11]
 [12 13]
 [14 15]]
[[ 76  82]
 [184 199]
 [292 316]
 [400 433]
 [508 550]]


In [129]:
print(a1)
print(a2)

[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]


In [130]:
# Element wise multiplication
r3 = np.multiply(a1,a2)
print(r3)

[[24 35  0]
 [ 8  9  0]
 [20  6 14]]


### Trignometric, Statistical functions

<img src="trigno_table.png">

In [142]:
a1 = np.sin(45*(np.pi/180))
a2 = int(np.cos(np.pi/2))
a3 = np.exp(1)
print(a1)
print(a2)
print(a3)

0.7071067811865476
0
2.718281828459045


In [139]:
n1 = np.log(2)
n2 = np.log10(2)
n3 = np.log2(2)
print(n1)
print(n2)
print(n3)

0.6931471805599453
0.3010299956639812
1.0
