In [1]:
import numpy as np

<img src="2d_indexing_slicing.png">

### 1D Indexing and Slicing

In [4]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25])
print(a)
print(len(a))
print(a.ndim)
print(a.shape)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
14
1
(14,)


### 1D Indexing

In [6]:
# Indexing in 1D array
print(a)
print(a[0]) # 12
print(a[4]) # 16
print(a[8]) # 20 
print(a[-2]) # 24 
print(a[-7]) # 19
print(a[-5]) # 21

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
12
16
20
24
19
21


### 1D Slicing
Syntax - array_name[start : end : step]

In [7]:
print(a)
print(a[2:5])
print(a[3:])
print(a[:6])
print(a[-4:])
print(a[:-6])
print(a[:])
print(a[1:8:2])
print(a[3:-7])
print(a[3:-7:2])
print(a[-2:-8:-2])
print(a[-2:3:-3])
print(a[3:8:3])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16]
[15 16 17 18 19 20 21 22 23 24 25]
[12 13 14 15 16 17]
[22 23 24 25]
[12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[13 15 17 19]
[15 16 17 18]
[15 17]
[24 22 20]
[24 21 18]
[15 18]


### 2D Indexing and Slicing

In [11]:
b = np.array([[31,32,33,34],[35,36,37,38],
              [39,40,41,42],[43,44,45,46]])
print(b)
print(b.ndim)
print(b.shape)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
2
(4, 4)


### 2D Indexing
In rows<br>
a) Left to Right traversal is equivalent to Top to bottom<br>
b) Right to Left traversal is equivalent to Bottom to Top<br>

<img src="2d_indexing_slicing.png">

In [13]:
print(b[2][0])    # 39
print(b[-1][-2])  # 45
print(b[2][-3])   # 40
print(b[-1][3])   # 46 
print(b[1,2])     # 37
print(b[0,3])     # 34
print(b[-3,-3])   # 36

39
45
40
46
37
34
36


### 2D Slicing
<b>Syntax - array_name[start_row : end_row : step_row , start_col : end_col :step_col]</b>

In [19]:
r = [12,13,14,15,16]
print(r[:-1])

[12, 13, 14, 15]


<img src="2d_indexing_slicing.png">

In [20]:
print(b[-1])
# print('--------')
print(b[:-1]) # all columns are sliced
# print('--------')
print(b[:,-1])
# print('--------')
print(b[-2,:-2])

[43 44 45 46]
[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]]
[34 38 42 46]
[39 40]


<img src="2d_indexing_slicing.png">

In [27]:
print(b[1:, 3:])
print(b[-2:,:-1])
print(b[1:,2:])
print(b[:2,0:])
print(b[::2,:])

[[38]
 [42]
 [46]]
[[39 40 41]
 [43 44 45]]
[[37 38]
 [41 42]
 [45 46]]
[[31 32 33 34]
 [35 36 37 38]]
[[31 32 33 34]
 [39 40 41 42]]


<img src="2d_indexing_slicing.png">

In [31]:
print(b[:2,::2])
print(b[1::2,1::2])
print(b[0::2,0::3])
print(b[-3::-1,-3])

[[31 33]
 [35 37]]
[[36 38]
 [44 46]]
[[31 34]
 [39 42]]
[36 32]


<img src="2d_indexing_slicing.png">

In [38]:
print(b[:2:-1,2::])
print(b[:1:-1])
print(b[:1:-1,:3])
print(b[:1:-1,2::-2])
print(b[:1:-2,2::-2])
print(b[0::3,0::3]) 
print(b[-1::-3,-1::-3])

[[45 46]]
[[43 44 45 46]
 [39 40 41 42]]
[[43 44 45]
 [39 40 41]]
[[45 43]
 [41 39]]
[[45 43]]
[[31 34]
 [43 46]]
[[46 43]
 [34 31]]


<img src="2d_indexing_slicing.png">

In [53]:
print(b[1:3,1:3])
print(b[-2:-4:-1,-1::-3])
print(b[-2::-2,-2:-4:-1])
print(b[-2::-2,-2:0:-1])

[[36 37]
 [40 41]]
[[42 39]
 [38 35]]
[[41 40]
 [33 32]]
[[41 40]
 [33 32]]


### 2D Advanced Indexing and Slicing

<img src="2d_indexing_slicing.png">

In [57]:
print(b[[0,1,2],[0,1,2]])
print(b[[0,1,2,3,0,3],[0,1,2,3,2,2]])
print(b[[0,1,2,3],[3,2,1,0]])
print(b[[1,2,-1,-2],[0,1,-2,-4]])

[31 36 41]
[31 36 41 46 33 45]
[34 37 40 43]
[35 40 45 39]


### 3D Indexing and Slicing

In [64]:
a = np.arange(32).reshape(2,4,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


### 3D Indexing

<img src="3d_indexing_slicing.png">

In [68]:
print(a[-2])
print(a[-1][-2])
print(a[-1][-2][-3]) # 25 
print(a[-1,2,2])     # 26
print(a[-2][0][-1])  # 3
print(a[1,3,2])      # 30

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 25 26 27]
25
26
3
30


### 3D Slicing
array_Name[set, row, col]<br>
array_name[start_set : end_set : step_set , start_row : end_row : step_row, start_col : end_col : step_col]

<img src="3d_indexing_slicing.png">

In [71]:
print(a[1:,1:,2:])
# print('----------')
print(a[1:,:2,:2])
# print('----------')
print(a[0:1,3:,1:])

[[[22 23]
  [26 27]
  [30 31]]]
[[[16 17]
  [20 21]]]
[[[13 14 15]]]


<img src="3d_indexing_slicing.png">

In [77]:
print(a[0:,1::2,:2])
print(a[1:,1::2,:2])
# # Negative slicing in 3d array
print(a[-1:,:,:])
print(a[:-1,:,:])

[[[ 4  5]
  [12 13]]

 [[20 21]
  [28 29]]]
[[[20 21]
  [28 29]]]
[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


<img src="3d_indexing_slicing.png">

In [81]:
print(a[-2,-1::-2,-1::-2])
print(a[-2:,-2::-2,-1::-2])
print(a[-2:,-1::-2,1])
print(a[-2:,-1::-3,-1::-2])

[[15 13]
 [ 7  5]]
[[[11  9]
  [ 3  1]]

 [[27 25]
  [19 17]]]
[[13  5]
 [29 21]]
[[[15 13]
  [ 3  1]]

 [[31 29]
  [19 17]]]


<img src="3d_indexing_slicing.png">

In [85]:
print(a[-2:,-1::-2,1:3])
print(a[:,::3,::2])
print(a[-2::,-4::3,-3::2])
print(a[-2::,-3:-1,1])

[[[13 14]
  [ 5  6]]

 [[29 30]
  [21 22]]]
[[[ 0  2]
  [12 14]]

 [[16 18]
  [28 30]]]
[[[ 1  3]
  [13 15]]

 [[17 19]
  [29 31]]]
[[ 5  9]
 [21 25]]


<img src="3d_indexing_slicing.png">

In [86]:
print(a[::-1,-2:-4:-1,-1::-2])
# print(a[0:,1:3,1:2])
# print(a[0:,::3,::2])
# print(a[-2:, -1::-3,-1::-2])

[[[27 25]
  [23 21]]

 [[11  9]
  [ 7  5]]]


<img src="3d_indexing_slicing.png">

In [89]:
print(a[::-1,-1::-3,-2:-4:-1])
print(a[::-1,0::3,0::3])

[[[30 29]
  [18 17]]

 [[14 13]
  [ 2  1]]]
[[[16 19]
  [28 31]]

 [[ 0  3]
  [12 15]]]


### 3D Advanced Indexing and Slicing

<img src="3d_indexing_slicing.png">

In [92]:
print(a[[0,0,0,0],[1,0,2,3],[1,3,1,2]])
print(a[[0,1,0,1],[1,2,3,0],[2,0,1,2]])
print(a[[0,0,0,0,1],[0,1,2,3,2],[0,1,2,2,1]])

[ 5  3  9 14]
[ 6 24 13 18]
[ 0  5 10 14 25]


In [93]:
x1 = a[a>9]
print(x1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]


In [94]:
x2 = a[a%3!=0]
print(x2)

[ 1  2  4  5  7  8 10 11 13 14 16 17 19 20 22 23 25 26 28 29 31]


#### Exercise

In [95]:
r = np.arange(2,77).reshape(3,5,5)
print(r)

[[[ 2  3  4  5  6]
  [ 7  8  9 10 11]
  [12 13 14 15 16]
  [17 18 19 20 21]
  [22 23 24 25 26]]

 [[27 28 29 30 31]
  [32 33 34 35 36]
  [37 38 39 40 41]
  [42 43 44 45 46]
  [47 48 49 50 51]]

 [[52 53 54 55 56]
  [57 58 59 60 61]
  [62 63 64 65 66]
  [67 68 69 70 71]
  [72 73 74 75 76]]]


<img src="3d_indexing_slicing2.png">