In [8]:
import numpy as np
from numpy import linalg

In [4]:
a = np.array([[2,3],[1,2]])
print(a)
print(a.shape)

[[2 3]
 [1 2]]
(2, 2)


In [5]:
a_inv = linalg.inv(a)
print(a_inv)

[[ 2. -3.]
 [-1.  2.]]


In [6]:
res = np.dot(a,a_inv)
print(res)

[[1. 0.]
 [0. 1.]]


#### Matrix Inverse
1) If A is a sqaure matrix,then there exists a mtarix B such that np.dot(A,B) = I where I is the inentity matrix

#### Trace
1) Sum of primary diagonal elements


In [14]:
h = np.array([[1,2,10],[4,5,6],[7,8,9]])
trace = np.trace(h)
print(h)
print(trace)

[[ 1  2 10]
 [ 4  5  6]
 [ 7  8  9]]
15


In [17]:
h = np.array([[1,2,10],[4,5,6],[7,8,9]])
rank = linalg.matrix_rank(h)
print(rank)

3


#### Matrix Decompose
<b>Av = λv</b>

where <br>
A = is the square matrix<br>
λ = Eigen value<br>
v = Eigen vectors

Original matrix A can be obtained from λ and v as follows
np.dot(np.dot(v,λ),inv(v))

Primary Diagnoal = Diagonal matrix elements starting from top left to bottom right.


In [25]:
print(a)
print(a.shape)

[[2 3]
 [1 2]]
(2, 2)


In [34]:
eig_val,eig_vec = linalg.eig(a)
print(eig_val)
print(eig_vec)
inv_eig_vec = linalg.inv(eig_vec) 
print(inv_eig_vec)

[3.73205081 0.26794919]
[[ 0.8660254 -0.8660254]
 [ 0.5        0.5      ]]
[[ 0.57735027  1.        ]
 [-0.57735027  1.        ]]


In [29]:
print(a)

[[2 3]
 [1 2]]


In [28]:
eval1 = np.array([[3.73205081,0],[0, 0.26794919]])
print(eval1)
r1 = np.dot(eig_vec,eval1)
print(r1)
r2 = np.dot(r1,linalg.inv(eig_vec))
print(r2)

[[3.73205081 0.        ]
 [0.         0.26794919]]
[[ 3.23205081 -0.23205081]
 [ 1.86602541  0.1339746 ]]
[[2. 3.]
 [1. 2.]]


In [33]:
eval1 = np.array([[3.73205081,0],[0, 0.26794919]])
print(eval1)
r1 = np.matmul(eig_vec,eval1)
print(r1)
inv_eig_vect = linalg.inv(eig_vec)
print(inv_eig_vect)
r2 = np.matmul(r1,inv_eig_vect)
print(r2)

[[3.73205081 0.        ]
 [0.         0.26794919]]
[[ 3.23205081 -0.23205081]
 [ 1.86602541  0.1339746 ]]
[[ 0.57735027  1.        ]
 [-0.57735027  1.        ]]
[[2. 3.]
 [1. 2.]]


In [32]:
res = (eig_vec@eval1)@linalg.inv(eig_vec)
print(res)

[[2. 3.]
 [1. 2.]]


#### Eigen value and Eigen Vector using Scipy

In [35]:
from scipy.linalg import eig as eigen

In [36]:
eig_val,eig_vec = eigen(a)
print(eig_val)
print(eig_vec)
inv_eig_vec = linalg.inv(eig_vec) 
print(inv_eig_vec)

[3.73205081+0.j 0.26794919+0.j]
[[ 0.8660254 -0.8660254]
 [ 0.5        0.5      ]]
[[ 0.57735027  1.        ]
 [-0.57735027  1.        ]]


In [ ]:
1) Read the data
2) Shape Checking
3) Null value Treatment
4) Univariate Data Analysis
5) Bivariate Data Analysis
6) Outlier Treatment
7) LabelEncoding or get_dummies
8) Feature Selection(using Multicollinearity chk) 
9) Split the data - train_test_split
10) PCA, if number of feature is very high
11) If Classification
 - Imbalanced Data handling - xsm,ysm for x_train,y_train
12) Model Building
13) Feature Selection (using Feature Importance - DT,RF)
14) Linearly Separable - LogReg, KNN,Boosting
15) Non-linearly separable - DT,RF,SVM,Boosting,KNN,NB
16) Cross Validation, HyperParameter Tuning - GridSearchCV, RandomizedSearchCV
17) Model Comparision based on performance - Accuracy, precision,Recall, ROC_AUC

18) If test_data.csv is present

a) Null value Treatment
b) Dupliacte treament
c) Feature Selection based on x_train.columns
d) LabelEncoding

In [ ]:
# Ex
# Train.csv - 1000 rows - 
# a) M1 -> x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=25)
# train m1 on x_train,y_train and generte predictions on x_test.
# Check model performance
# b) M2 -> train m2 on x and y using the best performing model from m1
# Test.csv  - 300 rows
# After data prepcocessing steps
# use m2 to generate predictions
# submission.csv

In [ ]:
# Model Deployment - 
# Model Retrain - 