### Feature Scaling and Standardization Methods

1) StandardScaler<br>
2) MinMaxScaler<br>
3) Normalize<br>

Example <br>
Age vs Income
            Age           Income
         (14 - 90)        varaible
No of     2 digits        (3-8) digits


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
d = {'Age':[18,23,45,56,67,39],
    'Income':[2300,54000,950,700000,35000,4800]}
df = pd.DataFrame(d)
df.head(6)

Age  Income
0   18    2300
1   23   54000
2   45     950
3   56  700000
4   67   35000
5   39    4800

### 1) StandardScaler
z = (x - u)/stdev

where<br>
z = standardized value<br>
x = individual value<br>
u = mean (column mean)<br>
stdev = std deviation (std_dev for column)

In [3]:
df1 = df.copy()
df1.head()

Age  Income
0   18    2300
1   23   54000
2   45     950
3   56  700000
4   67   35000

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
sc = StandardScaler()

In [6]:
df1_std = sc.fit_transform(df1)
print(df1_std)
print(type(df1_std))

[[-1.35724179 -0.51315357]
 [-1.06640426 -0.30992314]
 [ 0.21328085 -0.51846036]
 [ 0.85312341  2.22947456]
 [ 1.49296596 -0.3846113 ]
 [-0.13572418 -0.50332618]]
<class 'numpy.ndarray'>


In [7]:
df1.head(6)

Age  Income
0   18    2300
1   23   54000
2   45     950
3   56  700000
4   67   35000
5   39    4800

In [8]:
x23_std = (23 - df['Age'].mean())/df['Age'].std(ddof=0)
print(x23_std)
x35_std = (35000 - df['Income'].mean())/df['Income'].std(ddof=0)
print(x35_std)
# -0.3846113 

-1.066404259703037
-0.3846113049246541


### 2) MinMaxScaler

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))<br>
X_scaled = X_std * (max - min) + min

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
mmsc = MinMaxScaler() # default range is (0,1) min=0,max=1
df1_mmsc = mmsc.fit_transform(df1)
print(df1_mmsc)
print(type(df1_mmsc))

[[0.         0.00193119]
 [0.10204082 0.07588871]
 [0.55102041 0.        ]
 [0.7755102  1.        ]
 [1.         0.04870896]
 [0.42857143 0.00550747]]
<class 'numpy.ndarray'>


In [11]:
df1

Age  Income
0   18    2300
1   23   54000
2   45     950
3   56  700000
4   67   35000
5   39    4800

In [12]:
# X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
# X_scaled = X_std * (max - min) + min

In [13]:
x_std_56 = (56 - df1['Age'].min())/ (df1['Age'].max() - df1['Age'].min())
print(x_std_56)
x_sc_56 = x_std_56*(1-0) + 0
print(x_sc_56)
# 0.7755102

0.7755102040816326
0.7755102040816326


### Normalize

In [14]:
from sklearn.preprocessing import normalize

In [23]:
df = pd.DataFrame({'x':[1,2,3,4,5,6,7],'y':[4,8,6,10,14,12,16]})
df.head()

x   y
0  1   4
1  2   8
2  3   6
3  4  10
4  5  14

In [21]:
norml2 = normalize(df,norm='l2')
norml2

array([[0.24253563, 0.9701425 ],
       [0.24253563, 0.9701425 ],
       [0.4472136 , 0.89442719],
       [0.37139068, 0.92847669],
       [0.3363364 , 0.94174191],
       [0.4472136 , 0.89442719],
       [0.40081883, 0.91615733]])

In [29]:
1/(np.sqrt(1**2 + 4**2))

0.24253562503633297

In [22]:
norml1 = normalize(df,norm='l1')
norml1

array([[0.2       , 0.8       ],
       [0.2       , 0.8       ],
       [0.33333333, 0.66666667],
       [0.28571429, 0.71428571],
       [0.26315789, 0.73684211],
       [0.33333333, 0.66666667],
       [0.30434783, 0.69565217]])

In [28]:
print(2/(2+8),8/(2+8))

0.2 0.8


In [27]:
df.head(3)

x  y
0  1  4
1  2  8
2  3  6