### One Way ANOVA (Analyis of Variance)

1) A one-way ANOVA (“analysis of variance”) compares the means of three or more independent groups to determine if there is a statistically significant difference between the corresponding population means.


Steps in ANOVA<br>
1) <b>Calculate group mean and overall mean(mean of all the group mean obtained)</b><br>

2) <b>Compute SSR (Regression sum of squares)</b><br>
SSR = n * sum((individal_mean_of_each_group - overall_mean)^2)<br>
where n is the length of group (it is same for each group)

3) <b>Compute SSE(Error sum of squares)</b><br>
SSE = sum((xi - x_mean)^2)<br>
where <br>
xi = individual values of each group<br>
x_mean = mean of individal group<br>

4) <b>Compute SST (Total Sum of Squares)</b>
SST = SSR + SSE<br>

5) Populate the ANOVA Table
<img src="ANOVA_table1.png">

where <br>
n = total observations (sum of obersvtaions of each group), K = number of groups

6) Compare f_stat with f-critical at a given alpha value and df_t and df_er values<br>
7) Make inference for the hypothesis<br>

#### Q1)
We want to know whether or not three different exam prep programs lead to different mean scores on a certain exam. To test this, we recruit 30 students to participate in a study and split them into three groups.

The students in each group are randomly assigned to use one of the three exam prep programs for the next three weeks to prepare for an exam. At the end of the three weeks, all of the students take the same exam. The exam scores for each group are shown below:

Perform a one-way ANOVA test to determine if the mean exam score is different between the three groups.

<img src="anova_ex1.png" height="150" width="150" align="left">

In [1]:
import numpy as np
import math
import pandas as pd
import statistics as st

In [3]:
# 1) H0 (null hypothesis): μ1 = μ2 = μ3 = … = μk (all the population means are equal)
# 2) H1 (null hypothesis): at least one population mean is different from the rest

In [19]:
g1 = [85,86,88,75,78,94,98,79,71,80]
g2 = [91,92,93,85,87,84,82,88,95,96]
g3 = [79,78,88,94,92,85,83,85,82,81]

# Step 1
g1m,g2m,g3m = np.mean(g1),np.mean(g2),np.mean(g3)
print('g1_mean',g1m)
print('g2_mean',g2m)
print('g3_mean',g3m)
overall_mean = np.array([g1m,g2m,g3m]).mean()
print('Overall Mean',overall_mean)

# Step 2 - Between Group Variance
# Method - 1
ssr = len(g1)*(g1m-overall_mean)**2 + len(g2)*(g2m-overall_mean)**2 + len(g3)*(g3m-overall_mean)**2
print('SSR OR Between Group Variance:',ssr)
# Method - 2
ssr_m2 = len(g1)*sum([(i-overall_mean)**2 for i in [g1m,g2m,g3m]])
print('ssr_m2',ssr_m2)

# Step 3 - Within Group Variance
w1 = sum([(i-g1m)**2 for i in g1])
w2 = sum([(i-g2m)**2 for i in g2])
w3 = sum([(i-g3m)**2 for i in g3])
sse = w1+w2+w3
print('SSE or Within Group Varince',sse)

# Step 4 - Compute SST
sst = ssr + sse
print('SST', sst)

# Step 5 - compute df_t and df_err
n,k=30,3
df_t,df_er = k-1, n-k
print('dof_t',df_t)
print('dof_err',df_er)

# Step 6 - Compute ms_t, ms_err
ms_t,ms_err = ssr/df_t , sse/df_er
print('MS_t',ms_t)
print('MS_err',ms_err)

# Step 7 - Compute f_stat
f_stat = ms_t/ms_err
print('f_stat',f_stat)

f_crit = 3.35   # f_crit at dof(2,27) = 3.35
if f_stat>-f_crit and f_stat<f_crit:
    print('Ho is accepted')
else:
    print('Ho is rejected')

g1_mean 83.4
g2_mean 89.3
g3_mean 84.7
Overall Mean 85.8
SSR OR Between Group Variance: 192.19999999999948
ssr_m2 192.19999999999945
SSE or Within Group Varince 1100.6000000000001
SST 1292.7999999999997
dof_t 2
dof_err 27
MS_t 96.09999999999974
MS_err 40.762962962962966
f_stat 2.357532255133557
Ho is accepted


In [20]:
from scipy.stats import f_oneway

In [23]:
f_stat,p = f_oneway(g1,g2,g3)
print('f_stat',f_stat,'p',p)

f_stat 2.3575322551335636 p 0.11384795345837218


Since the F test statistic in the ANOVA table is less than the F critical value in the F distribution table, we fail to reject the null hypothesis. This means we don’t have sufficient evidence to say that there is a statistically significant difference between the mean exam scores of the three groups.

#### Q2) 
Apply One Way ANOVA using alpha=0.05

g1 = [210,240,270,270,300]<br>
g2 = [210,240,240,270,270]<br>
g3 = [180,210,210,210,240]


In [2]:
# 1) H0 (null hypothesis): μ1 = μ2 = μ3 = … = μk (all the population means are equal)
# 2) H1 (null hypothesis): at least one population mean is different from the rest

g1 = [210,240,270,270,300]
g2 = [210,240,240,270,270]
g3 = [180,210,210,210,240]



#### Q3)
Using the following data, perform a oneway ANOVA using α=0.05<br>
g1 = [51,45,33,45,67]<br>
g2 = [23,43,23,43,45]<br>
g3 = [56,76,74,87,56]


In [ ]:
# 1) H0 (null hypothesis): μ1 = μ2 = μ3 = … = μk (all the population means are equal)
# 2) H1 (null hypothesis): at least one population mean is different from the rest

In [3]:
g1 = [51,45,33,45,67]
g2 = [23,43,23,43,45]
g3 = [56,76,74,87,56]


#### Link Used -> http://rstudio-pubs-static.s3.amazonaws.com/228015_d8d0ddab79664707890681a9a75cf16d.html

#### Q3)
Perform ANOVA using the following summary at alpha = 0.05
<img src="anova_ex3.png">



In [3]:
import numpy as np

In [15]:
g1m,g2m,g3m = 50.26,45.32,53.67
lg1,lg2,lg3 = 30,30,30
sd1 ,sd2,sd3 = 10.45,12.76,11.47
n = lg1+lg2+lg3
k = 3
df_t = k - 1
df_err = n-k
print('df_t',df_t)
print('df_err',df_err)

overall_mean = np.array([g1m,g2m,g3m]).mean()
print('Overall_mean',overall_mean)

# SSR = n * sum((individal_mean_of_each_group - overall_mean)^2)
ssr = lg1 * sum([(i-overall_mean)**2 for i in [g1m,g2m,g3m]])
print('SSR- Between group variance',ssr)


# SSE
v1,v2,v3 = sd1**2,sd2**2,sd3**2
print('v1',v1,'v2',v2,'v3',v3)
w1,w2,w3 = v1*(lg1-1),v2*(lg2-1),v3*(lg3-1)
print('w1',w1,'w2',w2,'w3',w3)
sse = w1+w2+w3
print('SSE',sse)

# ms_t and ms_err
ms_t,ms_err = ssr/df_t , sse/df_err
print('MS_t',ms_t)
print('MS_err',ms_err)

# Step 7 - Compute f_stat
f_stat = ms_t/ms_err
print('f_stat',f_stat)

f_crit = 4.881
if f_stat>-f_crit and f_stat<f_crit:
    print('Ho is accepted')
else:
    print('Ho is rejected')

df_t 2
df_err 87
Overall_mean 49.75
SSR- Between group variance 1057.5420000000001
v1 109.20249999999999 v2 162.8176 v3 131.5609
w1 3166.8724999999995 w2 4721.7104 w3 3815.2661000000003
SSE 11703.849
MS_t 528.7710000000001
MS_err 134.52700000000002
f_stat 3.9305938584819407
Ho is accepted


#### Q4)
A clinical psychologist has run a between-subjects experiment comparing two treatments for depression (cognitive-behavioral therapy (CBT) and client-centered therapy (CCT) against a control condition. Subjects were randomly assigned to the experimental condition. After 12 weeks, the subject’s depression scores were measured using the CESD depression scale. The data are summarized as follows:

<img src="anova_ex4.png">

Use a oneway ANOVA with α=.01 for the test.

### Chi_Square Test of Independence

A Chi-Square Test of Independence is used to determine whether or not there is a significant association between two categorical variables.

Examples:-
We want to know if gender is associated with political party preference so we survey 500 voters and record their gender and political party preference.<br>
We want to know if a person’s favorite color is associated with their favorite sport so we survey 100 people and ask them about their preferences for both.<br>

Hypothesis<br>

    H0: (null hypothesis) The two variables are independent.
    H1: (alternative hypothesis) The two variables are not independent. (i.e. they are associated)

Formula for Chi_Square test

<img src="chi_square_formula.png">

where<br>
O = Observed Value<br>
E = Expected Value<br>
Expected value = (row sum * column sum) / table sum.

#### Q1)
We want to know whether or not gender is associated with political party preference. We take a simple random sample of 500 voters and survey them on their political party preference. Alpha = 0.05. 
The following table shows the results of the survey:-
<img src="chi_square_ex1.png" width="500">

### Solution
1) Compute the expected value
<img src="chi_square_ex1_expected_val.png" width="500">

2) Compute X2 (chi square values)
<img src="chi_square_ex1_chi_square_val.png" width ="500">

3) Calcuate the sum of X2 values obtained in step 2<br>
Sum = Σ(O-E)^2/E = 0.2174 + 0.2174 + 0.0676 + 0.0676 + 0.1471 + 0.1471 = 0.8642

4) dof_rows = (2-1) = 1, dof_col = (3-1) = 2<br>
dof = dof_rows * dof_cols = 1 * 2 = 2

5) The p-value associated with X2 = 0.8642 and dof 2 degrees of freedom is 0.649198


In [26]:
from scipy.stats import chi2_contingency

In [36]:
# H0: Gender and political party preference are independent.
# H1: Gender and political party preference are not independent
data = [[120,90,40],[110,95,45]]
alpha=0.05
chi_stat,p,dof,expected = chi2_contingency(data)
print('chi_stat',chi_stat)
print('p',p)
print('dof',dof)
print('expected\n',expected)
if p<alpha:
    print('Ho is rejected')
else:
    print('Ho is accepted')

chi_stat 0.8640353908896108
p 0.6491978887380976
dof 2
expected
 [[115.   92.5  42.5]
 [115.   92.5  42.5]]
Ho is accepted


Since this p-value is not less than 0.05, we fail to reject the null hypothesis. This means we do not have sufficient evidence to say that there is an association between gender and political party preference.

#### Q2) Test whether 'Gender' and 'Like Shopping' are independent. 
Gender =  ['F','F','F','M','M','F','F','M','M']<br>
Like Shopping = ['Y','N','Y','N','N','N','Y','Y','Y']

In [31]:
df =  pd.DataFrame({'Gender': ['F','F','F','M','M','F','F','M','M','F','M'],
              'Like Shopping':['Y','N','Y','N','N','N','Y','Y','Y','Y','N']})
df.head()
#          Like Shopping
# Gender     Y     N
#   M        2     3
#   F        4     2

Gender Like Shopping
0      F             Y
1      F             N
2      F             Y
3      M             N
4      M             N

In [34]:
# Ho: Gender and Like Shopping are independent.
# H1: Gender and Like Shopping are not independent.
contingency_table = pd.crosstab(df["Gender"],df["Like Shopping"])
contingency_table

Like Shopping  N  Y
Gender             
F              2  4
M              3  2

In [37]:
chi_stat,p,dof,expected = chi2_contingency(contingency_table)
print('chi_stat',chi_stat)
print('p',p)
print('dof',dof)
print('expected\n',expected)
alpha=0.05
if p<alpha:
    print('Ho is rejected')
else:
    print('Ho is accepted')

chi_stat 0.07638888888888876
p 0.782252069887464
dof 1
expected
 [[2.72727273 3.27272727]
 [2.27272727 2.72727273]]
Ho is accepted
